# fly.toml app configuration file generated for users-api-winter-river-6222 on 2025-08-30T14:34:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'users-api-winter-river-6222'
primary_region = 'cdg'

[env]
  SESSION_COOKIE_SECURE = 'true'
  SESSION_COOKIE_MAX_DAYS = '7'
  ADMIN_EMAILS = 'admin@example.org'
  CORS_ORIGINS = 'https://users-api-winter-river-6222.fly.dev'

[build]
[build.args]
  VITE_BASE_API_URL = 'https://users-api-winter-river-6222.fly.dev/api/v1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
